services:
  docs:
    image: pytitect_protocol_matrix_local_docs
    container_name: pytitect_protocol_matrix_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./pytitect_protocol_matrix:/app/pytitect_protocol_matrix:z
    ports:
      - '9000:9000'
    command: /start-docs
